### ISSUE TITLE
有没有办法能识别view包含二维码与否

### ISSUE THREAD

**Issue by DanteAndroid** [BolexLiu/PressScanCode#1]
像微信那样，然后动态加载菜单『识别二维码』

**Comment by BolexLiu** [comment]
可以的。在用户长按的时候先识别，如果有code返回说明该view里包含里一个二维码。则在菜单中显示『识别二维码』 。如果没有菜单中就无此选项。当用户点击该选项时再将之前识别到的二维码进行解析。
但是这个功能不应该被包含在本工具中。工具不该含业务。所以请自己实现。
