### ISSUE TITLE
能否加入一个识别是否是二维码的功能?

### ISSUE THREAD

**Issue by geekqian** [BolexLiu/PressScanCode#2]
如题. 
希望在选中图片时先做识别是否为二维码之后, 再进行解析.

**Comment by BolexLiu** [comment]
我明白你的意思，非常类似微信上的效果。但是这个轮子已经满足了。
你可以先扫描一次。如果有结果返回则表示有二维码。否则返回“”表示不是二维码。
String code= “123456”（ 或者 code= “”）
将结果的code记录下来。然后根据这个状态来告诉用户是否识别是二维码。
用户如果需要识别就将上次扫描好的二维码直接解析，并不需要再调用扫描一次。

**Comment by BolexLiu** [comment]
#1 和这个问题是同一个。
